#!/usr/bin/env bash
# A script that display subdomain information

display_subdomain() {
	local domain="$1"
	local subdomain="$2"
	local record_type
	# shellcheck disable=SC2086
	record_type=$(dig +short -t A "$subdomain.$domain" | awk '{print "A"}')
	local destination
	# shellcheck disable=SC2086
	destination=$(dig +short "$subdomain.$domain")
	echo "The subdomain $subdomain is a $record_type record and points to $destination"

}

# Main script
main() {
	local domain="$1"
	local subdomain="$2"

	if [ -n "$subdomain" ]; then
		display_subdomain "$domain" "$subdomain"
	else
		display_subdomain "$domain" "www"
		display_subdomain "$domain" "lb-01"
		display_subdomain "$domain" "web-01"
		display_subdomain "$domain" "web-02"
	fi
}
main "$@"
