#!/usr/bin/env bash

# Check if the number of parameters is less than 4
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

file_path=$1
server_ip=$2
username=$3
ssh_key=$4

# Transfer the file to the user's home directory on the server with scp
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username"@"$server_ip":~/

# Remotely execute the ls ~/ command via SSH to see what ~/ contains
ssh -i "$ssh_key" "$username"@"$server_ip" "ls ~/"
