#!/usr/bin/env bash
# Configure Nginx so that HTTP response contains a custom header
# Name of custom HTTP header must be X-Served-By
# Value of custom HTTP must be the hostname of the server Nginx is running on

# shellcheck disable=SC2154

apt-get -y update
apt-get -y install nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    add_header X-Served-By \$hostname;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location /404 {
    	root /etc/nginx/html;
	internal;
    }
}
" > /etc/nginx/sites-available/default

service nginx restart
