#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the following configurations:
#+    Enables management via the init script.
#+    Distributes requests using a round-robin algorithm.

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.4
apt-get -y update
apt-get install -y haproxy

printf %s "
	listen load_balancer
   	bind *:80
   	mode http
   	balance roundrobin
   	option httpclose
   	option forwardfor
	server 207806-web-01 54.144.129.181 check
	server 207806-web-02 100.26.226.16 check
" >> /etc/haproxy/haproxy.cfg

echo "ENABLED=1" >> /etc/default/haproxy

service haproxy start
