#!/usr/bin/env bash

# Check if the number of arguments provided is correct
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

ip_address="$1"

# Ping the specified IP address and display the result
ping -c 5 "$ip_address"
