#!/usr/bin/env bash
# Debugging while init must say that nginx is not running <- for real
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill -9 "$(cat /var/run/nginx.pid)"
