#!/usr/bin/env bash
# script that configures an Ubuntu server with the below requirements.
# changes the following domain resolve ips
# ----  localhost from 127.0.0.1 to 127.0.0.2
# ---- facebook.com from 157.240.229.35 to 8.8.8.8

if [ "$EUID" -ne 0 ]; then
	echo "Please run as root"
	exit 1

fi

cp /etc/hosts /etc/hosts.backup

sed -i '/localhost/d' /etc/hosts
sed -i '/facebook.com/d' /etc/hosts

echo "127.0.0.2 	localhost" >> /etc/hosts
echo "8.8.8.8   	facebook.com" >> /etc/hosts
